status-im/status-web

- .github/workflows/ci.yml
- packages/status-communities/src/messenger.spec.ts
Add some debug logging to investigate inconsistent CI failures.
> test: Add debug logging

- packages/status-communities/src/messenger.ts
Need testing with live Status Desktop. Blocked on new release of Status Desktop
> Add interface to retrieve previous messages

- packages/status-communities/src/messenger.ts
@Szymx95 FYI. Better use the Waku message timestamp for display than the `clock` or `timestamp` present on the chat message
> Provide message timestamp to caller

- packages/status-communities/src/chat.ts
- packages/status-communities/src/chat_message.spec.ts
- packages/status-communities/src/chat_message.ts
- packages/status-communities/src/messenger.ts
Just need to clarify if the `text` field can be presented for media messages.
> Add function to create media messages

- packages/status-communities/src/community.spec.ts
- packages/status-communities/src/encryption.spec.ts
- packages/status-communities/src/messenger.spec.ts
- packages/status-communities/src/messenger.ts
Also load messages from community chat.
However interoperability with Status Desktop is inconclusive.
https://github.com/status-im/dappconnect-chat-sdk/issues/5#issuecomment-949174057
> Instantiate all chats when instantiating community

- packages/react-chat-example/src/index.tsx
- packages/react-chat/src/components/Chat/ChatCreation.tsx
- packages/react-chat/src/components/Chat/ChatInput.tsx
- packages/react-chat/src/components/Chat/ChatTopbar.tsx
To create a chat, User can either click Confirm button or write a message and press enter.
> Add input to creation

- .husky/pre-commit
- package.json
- yarn.lock
Add pre-commit git hook together with [lint-staged](https://github.com/okonet/lint-staged) to run ESLint / Prettier on staged files before committing them.
> Add pre-commit git hook

- packages/status-core/.prettierignore
- packages/status-core/package.json
- packages/status-react/.mocharc.json
- packages/status-react/.prettierignore
- packages/status-react/buf.gen.yaml
- packages/status-react/buf.yaml
- packages/status-react/package.json
1. Removing some files that became obsolete due to simplification of Prettier configuration.
2. Clean up `package.json` scripts and dependencies that seemed to remain after copy & paste.
> Remove unused files and cleanup package.json

- packages/status-js/src/account.ts
- packages/status-js/src/client/member.ts
- packages/status-js/src/utils/compress-public-key.test.ts
- packages/status-js/src/utils/compress-public-key.ts
- packages/status-js/src/utils/public-key-to-color-hash.ts
- packages/status-react/src/components/member-sidebar/disconnect-dialog.tsx
- packages/status-react/src/components/member-sidebar/member-item.tsx
- packages/status-react/src/components/member-sidebar/user-item.tsx
- packages/status-react/src/components/user-profile-dialog/index.tsx
Enforce using of compressed public keys in the consumer-facing part. Status refers to them as chat keys: https://specs.status.im/spec/2#public-key-serialization.
> Use chat keys in the UI

- packages/status-js/src/client/chat.ts
- packages/status-js/src/client/community/community.ts
- packages/status-react/src/routes/chat/components/chat-message/index.tsx
This PR adds edit, delete and finishes request to join methods.
> Add more chat methods

- packages/status-js/src/client/chat.ts
- packages/status-js/src/client/community/community.ts
- packages/status-js/src/client/community/handle-waku-message.ts
- packages/status-js/src/client/community/map-chat-message.ts
- check owner, member and author
> Check owner, member and author prior handling

- packages/status-js/src/client/chat.ts
- packages/status-js/src/client/community/community.ts
- packages/status-js/src/client/community/handle-waku-message.ts
- packages/status-react/src/routes/chat/components/chat-message/index.tsx
- packages/status-react/src/routes/chat/components/chat-message/message-reply.tsx
- Use `Map`s for data structure of messages and their stashed actions (e.g. edit, delete)
- Sort messages and resolve replies prior callback
- Prevent emitting of messages from WakuStore
- Add clock per action to message type
> Update messages data structure

- .github/workflows/release.yml
- package.json
- yarn.lock
> note: not a pre-release flow
> note: add automation `NPM_TOKEN` as a secret to Settings > Secrets > Actions
if changesets exists in the repo:
- creates pull requests
- with version dependencies resovled
- and changelogs created
- keeps it up-to-date
- commits versioning result on merge
- publishes to npm
- creates git tags
- creates GitHub release
> add release workflow

- packages/components/src/accordion/accordion.stories.tsx
- packages/components/src/composer/composer.stories.tsx
- packages/components/src/topbar/topbar.stories.tsx
- Adds missing stories for topbar, composer and accordion components.
Tested in Storybook.
> feat: add missing stories

- apps/mobile/App.tsx
- apps/web/styles/app.css
- packages/components/src/accordion/accordion.stories.tsx
- packages/components/src/accordion/accordion.tsx
- packages/components/src/accordion/accordionItem.tsx
- packages/components/src/avatar/avatar.stories.tsx
- packages/components/src/avatar/avatar.tsx
- packages/components/src/button/button.stories.tsx
- packages/components/src/button/button.tsx
- packages/components/src/composer/composer.tsx
- packages/components/src/hooks/use-pressable-colors.tsx
- packages/components/src/icon-button/icon-button.stories.tsx
- packages/components/src/icon-button/icon-button.tsx
- packages/components/src/image/image.tsx
- packages/components/src/messages/components/actions.tsx
- packages/components/src/messages/message.tsx
- packages/components/src/popover/popover.stories.tsx
- packages/components/src/react-button/react-button.tsx
- packages/components/src/reply/reply.tsx
- packages/components/src/shadow/index.tsx
- packages/components/src/shadow/shadow.stories.tsx
- packages/components/src/shadow/shadow.tsx
- packages/components/src/sidebar/mock-data.tsx
- packages/components/src/sidebar/sidebar.tsx
- packages/components/src/tooltip/tooltip.stories.tsx
- packages/components/src/topbar/topbar.tsx
- packages/components/src/types.ts
- Reviewed and completed all variants of the following components:
- Button
- IconButton
- Avatar
- Added `Shadow` component based on [Foundations](https://www.figma.com/file/v98g9ZiaSHYUdKWrbFg9eM/Foundations?node-id=624-750&t=ETSJ2aq3bBx1Jszc-11) file.
- Add helper types for more constrained definitions of components props
- Make definitions of components more strict
- Add default variants
- Reviewed Replies feature.
> Review replies, update buttons, add shadow

- packages/components/src/dropdown-menu/dropdown-menu.tsx
- packages/components/src/topbar/topbar.tsx
Make styles consistent with the latest version in Figma.
> Update dropdown menu styles

- packages/status-js/src/index.ts
- packages/status-js/src/request-client/request-client.ts
Blocks https://github.com/status-im/community-dapp/pull/20
> Support array of public keys in `fetchCommunityDescription` 

- apps/website/src/components/datepicker/datepicker.tsx
- apps/website/src/pages/insights/epics/index.tsx
- packages/components/package.json
- packages/components/src/calendar/calendar.css
- packages/components/src/calendar/calendar.stories.tsx
- packages/components/src/calendar/calendar.tsx
- packages/components/src/calendar/components/caption.tsx
- packages/components/src/calendar/components/row.tsx
- packages/components/src/calendar/index.tsx
- packages/components/src/index.tsx
- yarn.lock
- Adds the calendar component to our components package. 
- Needs to be implemented in the burnup charts as a filter. WIP
- Works as single, multiple or range picker.
Tested in Next.js and Storybook
https://github.com/status-im/status-web/assets/29401404/ea91ef46-cb42-4826-9a6e-f73f5eafee03
> [website][status-web] Calendar

- apps/website/src/middleware.ts
> [website] add basic auth

- apps/website/src/config/routes.ts
- apps/website/src/pages/keycard.tsx
> [website] Add Keycard page

- apps/website/src/config/routes.ts
- apps/website/src/pages/brand.tsx
- apps/website/src/utils/rgb-to-hex.ts
~~waiting for #423~~
~~waiting for #431~~
> [website] Add Brand page

- .changeset/grumpy-cougars-cheer.md
- packages/components/src/tabs/tabs.tsx
- https://github.com/status-im/status-website/issues/459
> set TabsTrigger cursor

- .changeset/late-hotels-hide.md
- packages/status-js/src/client/client.ts
- packages/status-js/src/request-client/request-client.ts
- https://github.com/status-im/community-dapp/pull/102#discussion_r1389223770
> config `@libp2p/bootstrap`

- .changeset/fifty-years-kiss.md
- packages/status-js/package.json
- https://github.com/status-im/status-website/pull/698
> fix types export of multi entry point package

- .changeset/real-days-exist.md
- packages/components/src/toast/toast.tsx
- https://github.com/status-im/status-website/pull/698
> fix toast icon color

- packages/status-js/src/utils/public-key-to-eth-address.test.ts
- packages/status-js/src/utils/public-key-to-eth-address.ts
> note: based from u-protos-3-24 branch and https://github.com/status-im/status-web/pull/535 PR
> add `publicKeyToETHAddress` fn

- .changeset/brave-paws-promise.md
- .changeset/fluffy-maps-wait.md
- packages/status-js/src/client/community/is-encrypted.ts
- packages/status-js/src/request-client/request-client.ts
> note: based from `felicio:pk-eth` branch and https://github.com/status-im/status-web/pull/536 PR
> handle updates for encrypted communities

- .changeset/forty-wasps-refuse.md
- examples/with-next/pages/index.tsx
- examples/with-vite/src/app.tsx
- packages/status-js/src/client/client.ts
- packages/status-js/src/consts/peers.ts
- packages/status-js/src/request-client/request-client.ts
> note: review https://github.com/status-im/status-web/pull/541 first which this is based on
> compare: https://github.com/felicio/status-web/compare/handle-owner-token...felicio:status-web:query-seq
> iterate entity metadata sequentially
