status-im/status-web

CHANGELOG.md
README.md
package.json
packages/react-chat-example/package.json
packages/react-chat-example/src/index.html
packages/react-chat-example/src/index.tsx
packages/react-chat/package.json
packages/react-chat/src/components/CommunityChat.tsx
packages/react-chat/src/components/CommunityChatRoom.tsx
packages/react-chat/src/components/Form/ChannelMenu.tsx
packages/react-chat/src/components/Modals/WalletModal.tsx
packages/react-chat/src/groupChatComponents/DappConnectGroupChat.tsx
packages/react-chat/src/groupChatComponents/GroupChat.tsx
packages/react-chat/src/groupChatComponents/GroupChatRoom.tsx
packages/react-chat/src/index.ts
packages/react-group-chat-example/package.json
packages/react-group-chat-example/src/index.html
packages/react-group-chat-example/src/index.tsx
packages/status-communities/package.json
yarn.lock

Remove references to `DappConnect` and replace them with Waku Connect.
Instead of renaming the `DappConnectGroupChat` and `DappConnectCommunityChat` I adopted the following terminology:
- `*ChatRoom`: component that contains the chat, member list, channel list (if applicable)
- `*Chat`: Wraps the `*ChatRoom` component with the necessary themes and provider.

Rename DappConnect to Waku Connect

---

package.json
packages/status-core/package.json
packages/status-core/src/index.ts
packages/status-core/tsconfig.json
packages/status-react/package.json
packages/status-react/tsconfig.json
tsconfig.base.json
yarn.lock

Similarly to #225, this PR makes some changes for ease of maintainability.
1. Deduplicates as much as possible of TypeScript configuration between packages.
2. Moves TypeScript to the root of the monorepo.
3. Adds more strict rules
4. Fixes package.json target fields (previously pointing to non-existent bundles)

Improve TypeScript monorepo configuration

---

package.json
packages/status-core/package.json
packages/status-core/src/index.ts
packages/status-react/package.json
packages/status-react/src/components/Modals/ProfileFoundModal.tsx
packages/status-react/src/index.ts
yarn.lock

After researching many different tools for transpiling and building libraries, I decided to use [Parcel](https://parceljs.org) for now.
Other tools considered were:
- [tsdx](https://github.com/jaredpalmer/tsdx)
- [microbundle](https://github.com/developit/microbundle)
- [Vite](https://vitejs.dev/)
- [tsup](https://tsup.egoist.sh/)
- [Preconstruct](https://preconstruct.tools)
- ...
Parcel v2, released a couple of months ago, has [first-class support for libraries](https://parceljs.org/getting-started/library/), it uses an incredibly fast Rust-based compiler [SWC](https://swc.rs/) under-the-hood and it's already being used for examples.
This decision is not final and may change after I set up a process to measure the size of the library.

Use Parcel for building of packages

---

.eslintrc
packages/status-core/tsconfig.json
packages/status-react/tsconfig.json

Adds support for relative imports inside packages.
The relative path is not ideal, because Parcel [does not allow](https://parceljs.org/features/dependency-resolution) to specify different `baseUrl`, so relative paths have to start with `/src`. Since all code lies in the `src` folder, ideally it would be omitted.
For the sake of simplicity and maintainability, I don't want to mess with Parcel module resolution. ¯\_(ツ)_/¯

Support relative imports in packages

---

packages/status-js/src/client.ts
packages/status-react/src/routes/chat/components/chat-message/index.tsx
packages/status-react/src/routes/chat/index.tsx

Tried without internet connection to test that sent messages don't need to hit the network to be processed.
Also,
>emitSelf is "cheating" as it made your local app emit the message it sent as if it received it. It does nothing about ensuring the message is sent over the network. – https://discord.com/channels/864066763682218004/865466694554484738/937495906876526633
>if publish should emit to self, if subscribed – https://github.com/libp2p/js-libp2p-interfaces/blob/7e9caebab4dae2f92550db09f0a773b36b14a9c0/packages/interface-pubsub/src/index.ts#L89

Emit to self on send

---

packages/status-js/src/client/chat.ts
packages/status-js/src/helpers/contains-only-emoji.test.ts
packages/status-js/src/helpers/contains-only-emoji.ts

If a text message contains only emojis, it changes the content type to `EMOJI`.

Handle emoji content type

---

packages/status-js/src/client/client.ts

Relates to https://github.com/libp2p/js-libp2p/issues/939

Reestablish peer connection on silent stream destruction

---

apps/web/styles/reset.css
packages/components/.storybook/reset.css
packages/components/package.json
packages/components/src/counter/counter.tsx
packages/components/src/dialog/dialog.stories.tsx
packages/components/src/dialog/dialog.tsx
packages/components/src/dialog/index.tsx
packages/components/src/dynamic-button/dynamic-button.stories.tsx
packages/components/src/dynamic-button/dynamic-button.tsx
packages/components/src/hooks/use-pressable-colors.tsx
packages/components/src/icon-button/icon-button.tsx
packages/components/src/messages/components/reaction-popover.tsx
packages/components/src/messages/components/reactions-dialog.tsx
packages/components/src/messages/components/reactions.tsx
packages/components/src/pinned-message/pinned-message.tsx
packages/components/src/react-button/react-button.stories.tsx
packages/components/src/react-button/react-button.tsx
packages/components/src/sidebar-members/sidebar-members.tsx
packages/components/src/tabs/index.tsx
packages/components/src/tabs/tabs.stories.tsx
packages/components/src/tabs/tabs.tsx
packages/components/src/text/text.stories.tsx
packages/components/src/tooltip/tooltip.tsx
packages/components/src/types.ts
packages/components/src/user-list/user-list.tsx
yarn.lock

This PR reviews `reactions` feature, which includes
- reaction popover on the message
- reactions on the message
- adding reaction on the message
- correctly set selected and expanded states
Also,
**Implement Tabs component with optional icon**
**Update tooltip styles**
**Implement reactions dialog** (which correctly sets an initial tab based on the clicked reaction)

Review Reactions, add Tabs, update Tooltip

---

packages/components/package.json
packages/components/scripts/storybook.js

Storybook hangs on termination and forces manual stopping or using of another process with new port.
Dump of open handles (server and file watchers):
```
^C
SIGINT
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
- fd 1 (tty) (stdio)
- fd 2 (tty) (stdio)
- fd 0 (tty)
- Sockets:
- ::1:3001 -> ::1:54047
- ::1:3001 -> ::1:54054
- ::1:3001 -> ::1:54055
- ::1:3001 -> ::1:54056
- ::1:3001 -> ::1:54063
- Servers:
- :::3001 (HTTP)
- Listeners:
- request: app @ <project>/node_modules/@storybook/core-server/dist/index.js:31
- Others:
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- FSWatcher
- …
```

Terminate `storybook` on `SIGINT`

---

.changeset/dirty-books-argue.md
packages/components/src/button/button.stories.tsx
packages/components/src/button/button.tsx

This code:
was translated as this:
Color of button variant was automatically applied. But there are cases where we need to apply specific icon color. In case color is defined for icon, defined color is used.
In case it's icon only variant, classic color variant of button is applied.
After change:

fix: keep icon color if defined as part of button

---

.changeset/cold-jars-return.md
packages/components/src/button/button.tsx
packages/components/src/messages/components/reactions-dialog.tsx
packages/components/src/tabs/tabs.stories.tsx
packages/components/src/tabs/tabs.tsx

I opted-in into explicitly declaring a variant because there is no obvious "default". WDYT?
Removing `backdrop-blur` because of unexpected issues it is causing (example in the video):
https://github.com/status-im/status-web/assets/14926950/5a3f1ad6-1656-41bd-83c4-6e96b227a258

Add tabs variants and remove blur

---

packages/colors/package.json
packages/components/package.json
packages/icons/package.json

The motivation behind this change is so one can install the libs using the [Git Protocol](https://yarnpkg.com/protocol/git)

build: add `prepack` script in `packages/(components|colors/icons)`

---

.changeset/bright-students-taste.md
packages/status-js/src/utils/encode-url-data.test.ts
packages/status-js/src/utils/encode-url-data.ts

- https://github.com/status-im/status-website/issues/703

validate encoded data

---

.changeset/slow-doors-look.md
packages/components/src/icon-button/icon-button.tsx

It fixes bug, where color of the icon was not applied in the `<IconButton />` when used.
Usage of: 
`<OptionsIcon size={20} color="$danger-50" />`
Before:
After:

fix the color of the icon in IconButton

---

.changeset/lemon-dogs-lie.md
packages/components/src/tabs/tabs.stories.tsx
packages/components/src/tabs/tabs.tsx

This PR implements disabled state for Tabs.
It's necessary for implementation in Documentation.

add disabled state to Tabs

---

.changeset/early-ligers-act.md
packages/components/src/dropdown-menu/dropdown-menu.tsx

`<DropdowMenu.SubTrigger />` was missing a background highlight when expanded

fix `<DropdowMenu.SubTrigger />` expanded state

---

.changeset/stupid-pumpkins-grow.md
packages/components/src/button/button.tsx

fix `<Button />` text alignment

---

.changeset/few-suits-rescue.md
packages/components/src/tabs/tabs.tsx
packages/components/src/tag/tag.stories.tsx
packages/components/src/tag/tag.tsx

This PR changes:
Tag
- it doesn't show pointer cursor when there's no onPress event anymore
Tabs
- it enables to use Tooltip over Tabs for Documentation section

Fix tag and tabs

---

.changeset/early-apes-judge.md
packages/components/src/shortcut/shortcut.stories.tsx
packages/components/src/shortcut/shortcut.tsx

- unify how icon is passed with the rest of components
- fix error 
Also the symbol placement is centered now:

fix `<Shortcut />`

---

.changeset/famous-news-fry.md
packages/components/src/button/button.stories.tsx
packages/components/src/button/button.tsx

**Changes**
- Adds missing compound variants for icon styles for all use cases with iconOnly mode.
- Updated story to reflect icon use.

Icon only button - Fix color for all variants

---

.changeset/polite-cobras-accept.md
packages/colors/src/networks.ts
packages/components/src/dropdown-menu/dropdown-menu.tsx

This PR:
- fixes incorrect icon in DropdownMenu.SubTrigger component.
- fixes typo in networks
Figma:
Icon before:
Icon after:

fix `<DropdownMenu.SubTrigger>` icon; unknown network typo
